### ISSUE TITLE
Permission error during clone, if backup is in /root

### ISSUE THREAD

**Issue by bbuckingham** [RedHatSatellite/satellite-clone#180] opened 2017-04-07 21:23 UTC
Scenario:
- performed a backup of a Satellite 6.2 (el6) - used the https://github.com/RedHatSatellite/satellite-clone/blob/master/helpers/rhel_6_to_7_migration_backup.sh but modified to not include pulp content
- placed the backups in /root/satellite1_backup/
- performed a clone, configured for 'rhel_migration'

Result:
```
TASK [satellite-clone : Restore postgresql foreman database] *******************
Friday 07 April 2017  16:36:11 -0400 (0:00:00.416)       0:29:22.156 ********** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["runuser", "-", "postgres", "-c", "pg_restore -C -d postgres /root/satellite1_backup/katello_backup/foreman.dump"], "delta": "0:00:00.037578", "end": "2017-04-07 16:36:11.426698", "failed": true, "rc": 1, "start": "2017-04-07 16:36:11.389120", "stderr": "pg_restore: [archiver] could not open input file \"/root/satellite1_backup/katello_backup/foreman.dump\": Permission denied", "stdout": "", "stdout_lines": [], "warnings": []}

cmd: 
runuser
-
postgres
-c
pg_restore -C -d postgres /root/satellite1_backup/katello_backup/foreman.dump

start: 2017-04-07 16:36:11.389120

end: 2017-04-07 16:36:11.426698

delta: 0:00:00.037578

stderr: pg_restore: [archiver] could not open input file "/root/satellite1_backup/katello_backup/foreman.dump": Permission denied
	to retry, use: --limit @/root/satellite-clone/satellite-clone-playbook.retry

```

Based on discussion, it seems that the permission issue may be related to the backup being placed under /root.  If it had been in another location (e.g. /backup), it would not have caused trouble.

The following is the content of the backup directory:
```
# ls -al ~/satellite1_backup/katello_backup/
total 9482376
drwxrwx---. 2 root     postgres        161 Apr  7 16:06 .
drwxr-xr-x. 3 root     root             88 Apr  7 16:06 ..
-rw-r--r--. 1 postgres postgres     533013 Apr  7 09:50 candlepin.dump
-rw-r--r--. 1 root     root        1313268 Apr  7 09:43 config_files.tar.gz
-rw-r--r--. 1 root     root          35105 Apr  7 09:43 .config.snar
-rw-r--r--. 1 postgres postgres   12874614 Apr  7 09:50 foreman.dump
-rw-r--r--. 1 root     root     9695160320 Apr  7 09:47 mongo_data.tar.gz
-rw-r--r--. 1 root     root            367 Apr  7 09:47 .mongo.snar
-rw-r--r--. 1 root     root          20379 Apr  7 09:43 .postgres.snar

```

**Comment by sthirugn** [comment] 2017-04-10 15:47
I think this is a duplicate of https://github.com/RedHatSatellite/satellite-clone/issues/162.  Please reopen, if this is a different issue.

**Closed by sthirugn** 2017-04-10 15:47 UTC
